# Mod Properties

# Recommended Versioning Scheme: https://docs.neoforged.net/docs/gettingstarted/versioning/
version = 26.2.0.5

# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = pantryforblockheads

mod_name = Pantry for Blockheads

# Your group should be a unique identifier in reverse domain format.
group = net.blay09.mods

description=We have food mod at home. The missing counterpart to Cooking for Blockheads.

# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage = https://mods.twelveiterations.com/minecraft/pantry-for-blockheads
sources = https://github.com/TwelveIterations/PantryForBlockheads/issues
issues = https://github.com/TwelveIterations/PantryForBlockheads/issues
discord = https://discord.gg/VAfZ2Nau6j

# Make sure the license here matches the one you defined in the LICENSE file.
license=All Rights Reserved

mod_author = BlayTheNinth

# Credits can include other attribution as well, such as artists, etc.
credits = BlayTheNinth

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_project_id = 1514716
modrinth_project_id = Q0e0aOtQ
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# If you have a Maven to deploy to, configure its URLs here.
# maven_releases = https://
# maven_snapshots = https://

# Build Properties
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 25

# You can develop against published NeoForge snapshots (instead of releases) by adding the URL linked in the NeoForge PR here and updating the NeoForge version in gradle/libs.versions.toml.
neoforge_snapshot_url =

include_fabric=true
include_neoforge=true
include_forge=false

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
